from typing import Any, Dict, List, Optional, TypedDict
from pydantic import BaseModel, Field

class ParsedLog(BaseModel):
    """Structured information extracted from raw logs by the Regex Parser Agent."""
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    timestamps: List[str] = Field(default_factory=list)
    stack_traces: List[str] = Field(default_factory=list)
    stages: List[str] = Field(default_factory=list)
    job_names: List[str] = Field(default_factory=list)
    exit_codes: List[int] = Field(default_factory=list)

class ClassificationResult(BaseModel):
    """Failure classification from the DistilBERT Agent."""
    failure_type: str = "Unknown Failure"
    confidence: float = 0.0

class RootCauseResult(BaseModel):
    """Root cause analysis results from the Gemini Root Cause Agent."""
    root_cause: str = ""
    evidence: List[str] = Field(default_factory=list)
    confidence: float = 0.0

class RecommendedFix(BaseModel):
    """A recommended fix from the Remediation Agent."""
    fix: str
    priority: str = "high"
    explanation: str = ""

class RemediationResult(BaseModel):
    """Remediation details from the Gemini Remediation Agent."""
    recommended_fixes: List[RecommendedFix] = Field(default_factory=list)
    priority: str = "medium"

class FinalReport(BaseModel):
    """The final compiled analysis report generated by the Reporting Agent."""
    pipeline_platform: str = "Unknown"
    failure_type: str = "Unknown Failure"
    classification_confidence: float = 0.0
    root_cause: str = ""
    root_cause_confidence: float = 0.0
    evidence: List[str] = Field(default_factory=list)
    recommended_fixes: List[RecommendedFix] = Field(default_factory=list)
    summary: str = ""
    timestamp: str = ""

# Define the TypedDict state used by the LangGraph workflow
class AnalysisState(TypedDict, total=False):
    """LangGraph workflow state object."""
    raw_log: str
    metadata: Dict[str, Any]
    parsed_log: Optional[ParsedLog]
    classification: Optional[ClassificationResult]
    root_cause: Optional[RootCauseResult]
    reremediation: Optional[RemediationResult]  # Make sure we use remediation as standard
    remediation: Optional[RemediationResult]    # Support both spelling for robustness
    final_report: Optional[FinalReport]
    errors: List[str]
